name: khemra_scanner
description: "A Flutter package for Cambodian ID card scanning with camera, OCR, and image cropping."
version: 0.1.0
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2+1
  get: ^4.7.3
  image: ^4.8.0
  image_picker: ^1.2.1
  permission_handler: ^12.0.3
  path_provider: ^2.1.1
  http: ^1.6.0
  photo_manager: ^3.12.0
  native_opencv_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # To add assets to your package, add an assets section
